
export const GET_SERVICE_CARDS = 'GET_SERVICE_CARDS'
export const SET_SERVICE_FILTER = 'SET_SERVICE_FILTER'
export const SET_SERVICE_SEARCH = 'SET_SERVICE_SEARCH'
export const SET_TR_SERVICE_FILTER='SET_TR_SERVICE_FILTER'